In [28]:
from osgeo import gdal, osr
import numpy as np

In [29]:
def write_2d_tif(out_name, array):
    driver = gdal.GetDriverByName('GTiff')
    out_tif_name = out_name
    out_tif = driver.Create(out_tif_name, 1440, 600, 1, gdal.GDT_Float32, options=["COMPRESS=LZW"])

    # 设置影像的显示范围
    geotransform = (0.125, 0.25, 0, 89.875, 0, -0.25)  # ?????
    out_tif.SetGeoTransform(geotransform)

    # 获取地理坐标系
    srs = osr.SpatialReference()
    srs.ImportFromEPSG(4326)  # 定义输出的坐标系统为WGS84
    out_tif.SetProjection(srs.ExportToWkt())  # 给新建图层创建投影信息

    # 数据写出
    out_tif.GetRasterBand(1).WriteArray(array)
    out_tif.GetRasterBand(1).SetNoDataValue(np.nan)
    out_tif.FlushCache()
    # print(f'output successfully')
    del out_tif
    

In [30]:
ds = gdal.Open(r"H:\weather extreme\compound spei heatwave\tasmean_monthly\monthly_tas_ACCESS-CM2_historical_1950_01.tif")
gt = ds.GetGeoTransform()
proj = ds.GetProjection()

ref_arr = ds.ReadAsArray()

lat = np.arange(-59.875, 90.125, 0.25)[:,np.newaxis]
out_arr = np.repeat(lat, 1440, axis=1)[::-1, :]

In [31]:
write_2d_tif(r"H:\weather extreme\compound spei heatwave\latmask\latmask.tif", out_arr)

In [32]:
print(out_arr)

[[ 89.875  89.875  89.875 ...  89.875  89.875  89.875]
 [ 89.625  89.625  89.625 ...  89.625  89.625  89.625]
 [ 89.375  89.375  89.375 ...  89.375  89.375  89.375]
 ...
 [-59.375 -59.375 -59.375 ... -59.375 -59.375 -59.375]
 [-59.625 -59.625 -59.625 ... -59.625 -59.625 -59.625]
 [-59.875 -59.875 -59.875 ... -59.875 -59.875 -59.875]]
